### ISSUE TITLE
Support tmysql4

### ISSUE THREAD

**Issue by Kamshak** [Kamshak/LibK#11]
Need to add support for tmysql4 and mysqloo
- [ ] Adjust module checking to check for both (tmysql and mysqloo), error only when one isn't present
- [ ] Add Support for tmysql to the db wrapper: Check for existing solutions
- [ ] Test connection is reistablished after failure and queued queries are executed
- [ ] Eliminate all blocking calls (e.g. Updater)

**Comment by SirNickParks** [comment]
If i'm using the tmysql mysqloo wrapper that was made ([link](https://facepunch.com/showthread.php?t=1357773&p=48902069&viewfull=1#post48902069) How come it still produces this error?

[ERROR] addons/libk/lua/libk/server/sv_libk_database.lua:113: attempt to index field 'MySQLDB' (a nil value)
  1. Query - addons/libk/lua/libk/server/sv_libk_database.lua:113
   2. DoQuery - addons/libk/lua/libk/server/sv_libk_database.lua:167
    3. s - addons/libk/lua/libk/server/sv_libk_model.lua:145
     4. succ - addons/libk/lua/libk/shared/1_sh_promises.lua:48
      5. Done - addons/libk/lua/libk/shared/1_sh_promises.lua:116
       6. initializeTable - addons/libk/lua/libk/shared/1_sh_promises.lua:107
        7. initModels - addons/libk/lua/libk/server/sv_libk_server.lua:52
         8. v - addons/libk/lua/libk/server/sv_libk_server.lua:69
          9. Call - lua/includes/modules/hook.lua:84
           10. onConnected - addons/libk/lua/libk/server/sv_libk_database.lua:255
            11. connect - lua/includes/modules/mysqloo.lua:55
             12. ConnectToMySQL - addons/libk/lua/libk/server/sv_libk_database.lua:257
              13. getDatabaseConnection - addons/libk/lua/libk/server/sv_libk_database

**Comment by Kamshak** [comment]
@SirNickParks It's because it doesn't support any blocking connections unfortunately.

**Comment by Kamshak** [comment]
Closing this as tmysql is no longer maintained and mysqloov9 is a full recode and the recommended module now.
