### ISSUE TITLE
transfers.lua:129: attempt to index local 'inboundTransfer' (a nil value)

### ISSUE THREAD

**Issue by markusmarkusz** [Kamshak/LibK#17]
```
[ERROR] addons/libk/lua/libk/3rdparty/glib/transfers/transfers.lua:129: attempt to index local 'inboundTransfer' (a nil value)
  1. unknown - addons/libk/lua/libk/3rdparty/glib/transfers/transfers.lua:129
   2. fn - addons/libk/lua/libk/3rdparty/glib/transfers/vnet.lua:1611
    3. unknown - addons/ulib/lua/ulib/shared/hook.lua:110
```
I'm sure the error message is better off here, as the message was apparently triggered by LibK or an addon that uses LibK (example: Pointshop 2).
It could be that the error was already fixed, since the message is already older.
A nil check is probably not the best solution in this case, since this error can only occur if [messageType](https://github.com/Kamshak/LibK/blob/master/lua/libk/3rdparty/glib/transfers/transfers.lua#L74) is not `1` or `2`.

**Comment by Kamshak** [comment]
Should have been fixed in a GLib update, please reopen if you run across this again
