### ISSUE TITLE
[LibK] FATAL: Couldn't load mysqloo, make sure it is correctly installed! errror was: attempt to index a string value

### ISSUE THREAD

**Issue by mbaehr2909** [Kamshak/LibK#19]
Nach dem Installieren des Pointshop 2 und Konfigurieren auf die Nutzung von mySQL spuckt er den im Titel genannten Fehler raus. Auch werden die Tables nicht erstellt, weshalb er sich nicht mit den Tables verbinden kann.

Hier ein Auszug aus dem libk Error Log:
Wed Sep 20 15:28:47 2017 - [LibK] FATAL: Couldn't load mysqloo, make sure it is correctly installed! errror was: attempt to index a string value
Wed Sep 20 15:28:47 2017 - MySQL Error: MySQLOO modules aren't installed properly!
Wed Sep 20 15:28:54 2017 - [LibK] Error initializing player Hardwave3[DTJ](0: SQL Error )
Wed Sep 20 15:28:55 2017 - [LibK] Error initializing player Pickle Rick(0: SQL Error )

**Comment by Kamshak** [comment]
MySQLoo ist nicht richtig installiert, bitte nochmal Installation checken. Hab dir auch im Forum schon geantwortet

**Comment by mbaehr2909** [comment]
Das habe ich bereits gemacht. Auch habe ich den server komplett neu aufgesetzt und dann nur mit dem PointShop und erforderlichen Dateien gearbeitet. Immer wieder kommt dieselbe Fehlermeldung.

**Comment by Kamshak** [comment]
Kann dir leider nicht mehr sagen, ist kein LibK Problem sondern entweder etwas mit der Installation des Moduls oder ein Problem mit dem Modul selber. Du kannst das so testen:

```
lua_run require([[mysqloo]])
```
