### ISSUE TITLE
Error - no MetaName string type for userdata (AGH!)

### ISSUE THREAD

**Issue by monster010** [Kamshak/LibK#22]
heyho,

I would find it nice, if the error "Error - no MetaName string type for userdata (AGH!)" would finally be fixed and would not stand about 90000 times in a log, after each map change.

**Comment by Kamshak** [comment]
Hey, would like that as well. As far as i can tell it originates from GMOD and is triggered by the MySQLOO module.

**Comment by monster010** [comment]
The funny thing is that it is triggered only at Pointshop 2 or Libk and no other addon.

**Comment by Kamshak** [comment]
This will be gone in the next gmod version see #3452
