### ISSUE TITLE
Apologies for this

### ISSUE THREAD

**Issue by Thepenguin9** [Kamshak/LibK#26]
I am just curious as to whether you have plans to release the code for Pointshop 2? I'm trying to find a legit version of your addon, or one on par with it and I simply cannot find one.

Apologies for hijacking an issue with this request, I know of no other way to contact you

**Comment by Kamshak** [comment]
Hey, will get back to you on this - could you shoot me an email to kamshak@pointshop2.com with your usecase? (single community, multiple communities, as developer / as owner, ...)

Thanks
