### ISSUE TITLE
Pointshop2 Version {{ script_id }} : {{ user_id }} loaded Couldn't include file 'includes\modules\mysqloo.lua' (File not found) (<nowhere>) [LibK] FATAL: Couldn't load mysqloo, make sure it is correctly installed! errror was: Module not found! MySQL Error: MySQLOO modules aren't installed properly!

### ISSUE THREAD

**Issue by DamienFoulon** [Kamshak/LibK#30]
Hello,

I have places the gmsv_mysqloo_win64.dll in the "garrysmod/lua/bin" folder and the libmySQL.dll in the root file wich is the srcds.exe. So the mysqloo should be installed correctly but...

I get this error at the start of the server :

Couldn't include file 'includes\modules\mysqloo.lua' (File not found) (<nowhere>)
[LibK] FATAL: Couldn't load mysqloo, make sure it is correctly installed! errror was: Module not found!
MySQL Error: MySQLOO modules aren't installed properly!

Someone have an idea or a solution ?

**Comment by JustPlayerDE** [comment]
You need to follow the instructions: https://github.com/FredyH/MySQLOO#install-instructions

you may use a outdated version.
(you dont need libMySQL anymore)
