### ISSUE TITLE
uncaught error in Promise

### ISSUE THREAD

**Issue by Zulbem** [Kamshak/LibK#32]
First time I've seen this pop up in the console... Not sure if I should ignore it but thought I'd forward it to you.

```
WARNIG: uncaught error in Promise: -2
1: () [addons/libk/lua/libk/shared/1_sh_promises.lua: 321]
```

**Comment by Oyplap** [comment]
I got this

WARNIG: uncaught error in Promise: -2
 1: () [addons/libk-master/lua/libk/shared/1_sh_promises.lua: 321]
 2: xpcall (GLib.Error) [[C]: -1]
 3: () [addons/libk-master/lua/libk/3rdparty/glib/threading/thread.lua: 262]

**Comment by Kamshak** [comment]
Do you get any errors further down because of it? It looks like this could happen if a db is not loaded but not sure what that would mean https://github.com/Kamshak/LibK/blob/3cff2a020d06b629a747bfcb5238da4bfad46922/lua/libk/server/sv_libk_model.lua#L72

**Comment by Oyplap** [comment]
Nah i think some other addon is interfering with it because when i remove discord integration, it doesn't show that error no more.
