### ISSUE TITLE
Problem with the LibK with the newest pre-release version of Mysqloo

### ISSUE THREAD

**Issue by SandeQ** [Kamshak/LibK#33]
Hi

I have a problem with the newest testing version of mysqloo, i'm getting some LibK error, i'm not sure if the error is mysqloo related, so i'm writing to both of you :)

I've downloaded the x64 gmod linux server, put the gmsv_mysqloo_linux64.dll in garrysmod/lua/bin folder, and the libmysqlclient.so in the main folder, next to srcds files.

Now i'm getting such error

[LibK] FATAL: Couldn't load mysqloo, make sure it is correctly installed! errror was: Couldn't load module library!
MySQL Error: MySQLOO modules aren't installed properly!

What have i done wrong? I think i've placed the files in good folders, can it be something with LibK?

![image](https://user-images.githubusercontent.com/29819929/87101792-4dffbf80-c250-11ea-9c86-e42cfdacf1d9.png)
bin folder
![image](https://user-images.githubusercontent.com/29819929/87102027-e302b880-c250-11ea-93ad-0b93a57be206.png)
gmod main folder

On the screen the file belongs to another user, but even after chowning it, it won't work

The server start script looks like that, i'm not sure if it would help

./srcds_run_x64 -port 4420 -game garrysmod +maxplayers 35 +map ttt_rooftops_2016_v1 +host_workshop_collection <id_of_collection> +gamemode terrortown -nobots -ignoresigint +sv_setsteamaccount <some_id> -threads 8 +exec autoexec.cfg

**Comment by Kamshak** [comment]
I think this should be good now https://github.com/Kamshak/LibK/pull/39
