### ISSUE TITLE
Can't change active items in pointshop2

### ISSUE THREAD

**Issue by ChrisBkt** [Kamshak/LibK#48]

**Comment by ChrisBkt** [comment]
Following error in the console when i try to activate a item:

`addons/libk/lua/libk/server/sv_libk_database.lua:171: attempt to call local 'callback' (a table value)
                 1: Query (sqlText = "UPDATE `kinv_items` SET  `itemclass` = 'KInventory.Items.17',`data` = '{\"purchaseData\":{\"amount\":3600.0,\"time\":1703465528.0,\"currency\":\"points\",\"origin\":\"LUA\"}}',`itempersistence_id` = '17',`inventory_id` = '1' WHERE `id` = '4'", callback = _R._LOADED.team:callback, errorCallback = function (error), blocking = nil) [addons/libk/lua/libk/server/sv_libk_database.lua: 171]
                 2: add (self = { _R._LOADED.team:LibK.TransactionSqlite.__instanceDict: 0xeaddbef2 }, sqlText = "UPDATE `kinv_items` SET  `itemclass` = 'KInventory.Items.17',`data` = '{\"purchaseData\":{\"amount\":3600.0,\"time\":1703465528.0,\"currency\":\"points\",\"origin\":\"LUA\"}}',`itempersistence_id` = '17',`inventory_id` = '1' WHERE `id` = '4'") [addons/libk/lua/libk/server/sv_database_transaction.lua: 77]
                 3: s () [addons/pointshop2/lua/ps2/server/sv_pointshopcontroller_shop.lua: 390]
                 4: succ () [adLUA Error in Controller Pointshop2Controller action unequipItem:

nil`

**Comment by ValentinFunk** [comment]
I think we solved this in Discord?
