### ISSUE TITLE
LibK Error

### ISSUE THREAD

**Issue by SenipSenni** [Kamshak/LibK#5]
194(8.956072):  Couldn't include file libk/3rdparty/currency/icurrencysystem.lua -> libk/3rdparty/glib/currency/icurrencysystem.lua

193(8.955789):  L 12/01/2015 - 03:11:19: Lua Error: Couldn't include file libk/3rdparty/currency/icurrencysystem.lua -> libk/3rdparty/glib/currency/icurrencysystem.lua

**Comment by Kamshak** [comment]
I honestly have no idea why this isn't working, looked into it a while ago but i don't use the interface so I always ignored this error. Shouldn't cause anything but that message unless you were planning to use the class.

**Comment by comedinha** [comment]
No have file on libk/3rdparty/currency

**Comment by Kamshak** [comment]
Fixed
