### ISSUE TITLE
LibK causing a nil value

### ISSUE THREAD

**Issue by Polarcraft** [Kamshak/LibK#7]
So I don't know how this is coming up, but apparently I keep getting this error. Sorry for not giving enough details, just curious if I need glib or if it is a config issue.

addons/libk/lua/libk/3rdparty/glib/loader/loader.lua:321: attempt to index a nil value

The line that it is showing that is nil would be:
	if not GetConVar ("sv_allowcslua"):GetBool () then return true end

**Comment by Kamshak** [comment]
Can't reproduce this, I have updated GLib in the repo which might have fixed the issue.
